// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package rank

import (
	"CSIE_ADMS_Back-End/api/rank"
)

type ControllerV1 struct{}

func NewV1() rank.IRankV1 {
	return &ControllerV1{}
}
