// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"CSIE_ADMS_Back-End/internal/dao/internal"
)

// internalAdmissionMethodsDao is internal type for wrapping internal DAO implements.
type internalAdmissionMethodsDao = *internal.AdmissionMethodsDao

// admissionMethodsDao is the data access object for table admission_methods.
// You can define custom methods on it to extend its functionality as you wish.
type admissionMethodsDao struct {
	internalAdmissionMethodsDao
}

var (
	// AdmissionMethods is globally public accessible object for table admission_methods operations.
	AdmissionMethods = admissionMethodsDao{
		internal.NewAdmissionMethodsDao(),
	}
)

// Fill with you ideas below.
