// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"CSIE_ADMS_Back-End/internal/dao/internal"
)

// internalAdmissionGroupsDao is internal type for wrapping internal DAO implements.
type internalAdmissionGroupsDao = *internal.AdmissionGroupsDao

// admissionGroupsDao is the data access object for table admission_groups.
// You can define custom methods on it to extend its functionality as you wish.
type admissionGroupsDao struct {
	internalAdmissionGroupsDao
}

var (
	// AdmissionGroups is globally public accessible object for table admission_groups operations.
	AdmissionGroups = admissionGroupsDao{
		internal.NewAdmissionGroupsDao(),
	}
)

// Fill with you ideas below.
