// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"CSIE_ADMS_Back-End/internal/dao/internal"
)

// internalCitiesDao is internal type for wrapping internal DAO implements.
type internalCitiesDao = *internal.CitiesDao

// citiesDao is the data access object for table cities.
// You can define custom methods on it to extend its functionality as you wish.
type citiesDao struct {
	internalCitiesDao
}

var (
	// Cities is globally public accessible object for table cities operations.
	Cities = citiesDao{
		internal.NewCitiesDao(),
	}
)

// Fill with you ideas below.
