// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"CSIE_ADMS_Back-End/internal/dao/internal"
)

// internalDegreesDao is internal type for wrapping internal DAO implements.
type internalDegreesDao = *internal.DegreesDao

// degreesDao is the data access object for table degrees.
// You can define custom methods on it to extend its functionality as you wish.
type degreesDao struct {
	internalDegreesDao
}

var (
	// Degrees is globally public accessible object for table degrees operations.
	Degrees = degreesDao{
		internal.NewDegreesDao(),
	}
)

// Fill with you ideas below.
