// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"CSIE_ADMS_Back-End/internal/dao/internal"
)

// internalGsatScoreDao is internal type for wrapping internal DAO implements.
type internalGsatScoreDao = *internal.GsatScoreDao

// gsatScoreDao is the data access object for table gsat_score.
// You can define custom methods on it to extend its functionality as you wish.
type gsatScoreDao struct {
	internalGsatScoreDao
}

var (
	// GsatScore is globally public accessible object for table gsat_score operations.
	GsatScore = gsatScoreDao{
		internal.NewGsatScoreDao(),
	}
)

// Fill with you ideas below.
