// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"CSIE_ADMS_Back-End/internal/dao/internal"
)

// internalSemesterRankDao is internal type for wrapping internal DAO implements.
type internalSemesterRankDao = *internal.SemesterRankDao

// semesterRankDao is the data access object for table semester_rank.
// You can define custom methods on it to extend its functionality as you wish.
type semesterRankDao struct {
	internalSemesterRankDao
}

var (
	// SemesterRank is globally public accessible object for table semester_rank operations.
	SemesterRank = semesterRankDao{
		internal.NewSemesterRankDao(),
	}
)

// Fill with you ideas below.
