// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"CSIE_ADMS_Back-End/internal/dao/internal"
)

// internalStarPlanDao is internal type for wrapping internal DAO implements.
type internalStarPlanDao = *internal.StarPlanDao

// starPlanDao is the data access object for table star_plan.
// You can define custom methods on it to extend its functionality as you wish.
type starPlanDao struct {
	internalStarPlanDao
}

var (
	// StarPlan is globally public accessible object for table star_plan operations.
	StarPlan = starPlanDao{
		internal.NewStarPlanDao(),
	}
)

// Fill with you ideas below.
