// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"CSIE_ADMS_Back-End/internal/dao/internal"
)

// internalYearsRankDao is internal type for wrapping internal DAO implements.
type internalYearsRankDao = *internal.YearsRankDao

// yearsRankDao is the data access object for table years_rank.
// You can define custom methods on it to extend its functionality as you wish.
type yearsRankDao struct {
	internalYearsRankDao
}

var (
	// YearsRank is globally public accessible object for table years_rank operations.
	YearsRank = yearsRankDao{
		internal.NewYearsRankDao(),
	}
)

// Fill with you ideas below.
